enabled_regions:
- Вінницька
- Волинська
- Дніпропетровська
- Донецька
- Житомирська
- Закарпатська
- Запорізька
- Івано-Франківська
- Кіровоградська
- Луганська
- Миколаївська
- Одеська
- Полтавська
- Рівненська
- Сумська
- Тернопільська
- Харківська
- Херсонська
- Хмельницька
- Черкаська
- Чернівецька
- Чернігівська
- Київ
