# -*- coding: utf-8 -*-
# Коди класифікації CAV для фільтрації аукціонів ProZorro.Sale
# Формат: код: опис

classification_codes:
  - code: '04000000-8'
    description: 'Нерухоме майно'
  - code: '04233000-0'
    description: 'Адміністративні приміщення в житлових будинках'
  - code: '04230000-9'
    description: 'Адміністративно-офісна нерухомість'
  - code: '04130000-8'
    description: 'Гуртожиток, житловий будинок коридорного, у тому числі галерейного, готельного типу (будинок для малосімейних) та його частини'
  - code: '04232000-3'
    description: 'Адміністративна будівля, приміщення в адміністративній будівлі'
  - code: '70123000-9'
    description: 'Продаж нерухомості'
  - code: '70123200-1'
    description: 'Продаж нежитлової нерухомості'
  - code: '04222000-0'
    description: 'Магазин (гастроном, універмаг, мінімаркет), аптека, перукарня, хімчистка, пральня, лікарняно-оздоровчий заклад, фізкультурно-оздоровчий заклад тощо'
  - code: '06000000-2'
    description: 'Земельні ділянки'
  - code: '04211000-0'
    description: 'Промислова заводська, фабрична будівля та їх частини'
  - code: '06111000-3'
    description: 'Землі житлової забудови (землі, які використовуються для розміщення житлової забудови (житлові будинки, гуртожитки, господарські будівлі та інше); землі, які використовуються для розміщення гаражного будівництва)'
  - code: '06112000-0'
    description: "Землі громадської забудови (землі, які використовуються для розміщення громадських будівель і споруд (готелів, офісних будівель, торговельних будівель, для публічних виступів, для музеїв та бібліотек, для навчальних та дослідних закладів, для лікарень та оздоровчих закладів), інших об'єктів загального користування)"
  - code: '05000000-5'
    description: 'Цілісний майновий комплекс або майновий комплекс - комплекс активів підприємства'
  - code: '06110000-6'
    description: 'Земельні ділянки призначені для забудови'
  - code: '06128000-5'
    description: "Землі промисловості, транспорту, зв'язку, енергетики, оборони та іншого призначення"
